### ISSUE TITLE
Yubikey config: check for security key

### ISSUE THREAD

**Issue by arunoruto** [EmergentMind/nix-config#14]
First and foremost, thanks for the awesome [Yubikey on NixOS](https://www.youtube.com/watch?v=3CeXbONjIgE) video! Hope to see more in the future (maybe TPM?).

Now, onto the issue:
https://github.com/EmergentMind/nix-config/blob/7cc7105799731af439d8baba533bb29290b8cc33/modules/nixos/yubikey/default.nix#L24
If I have two keys plugged in, and one of them is a [security key](https://www.yubico.com/products/security-key/), it would misidentify a part of the `ykman list` command as its serial, since this line of keys [does not have a serial number](https://docs.yubico.com/yesdk/users-manual/application-otp/commands-get-serial.html).

I suggest to swap the awk command with `sed`:
```sh
ykman list | sed -nE 's/.* Serial: ([0-9]+)/\1/p'
```

Here is an example of both commands with two Yubikeys plugged in, one security key, and one from the 5 series:
```sh
$ ykman list
YubiKey 5C NFC (5.7.1) [OTP+FIDO+CCID] Serial: 12345678
Security Key NFC (5.2.4) [FIDO]

$ ykman list | awk '{print $NF}'
12345678
[FIDO]

$ ykman list | sed -nE 's/.* Serial: ([0-9]+)/\1/p'
12345678
```

There are two approaches on how to handle security keys here:
1. Easy: expect that users have only one security key and make it the default if no serial has been detected
2. A bit harder: if there are multiple ones, or one does not want to default to a key, the firmware value could be identified and tied to a key (ofc if no serial value has been found)

The second method would have something like the following `sed` command to check for the firmware version:
```sh
$ ykman list | sed -nE 's/.* \(([0-9]+.[0-9]+.[0-9]+)\) .*/\1/p'
5.7.1
5.2.4
```
If the user has multiple security keys but different firmware, they could be used to differentiate the keys.

**Caveat**: Your current script differentiates between the Yubikey 4 and 5 series. I am not sure if both can be enabled and if additional scripting would be needed for the security key series.

**Comment by EmergentMind** [comment]
Thanks for this! Good suggestion. I'll likely take a deeper look over the weekend.

**Comment by EmergentMind** [comment]
The approach of assuming a user only has one security key seems like a reasonable first iteration, at least until we know someone needs support for multiples.

That said, we either default to the security key when no serials are detected (as you suggest) or perhaps just use `[FIDO]` as a mock serial value for detecting when the security is present.

The downside of defaulting to security key is that if an auth request occurs when the security key is not actually plugged in then the user would have to wait for the timeout before moving on. This would be counter to the primary intent of the script.

By using the '[FIDO]' value as a mock serial value we can detect when the security key is plugged in/"up" and only associate it with the proxy ssh key when it is actually plugged in. The down side being it is a bit gross to use "[FIDO]" as a serial value.

Any thoughts on that perspective? I'm leaning towards the latter because it maintains the utility of the script. Just needs some documentation to explain the use case, which I'm happy to add.

**Comment by EmergentMind** [comment]
Completed in [acac39d](https://github.com/EmergentMind/nix-config/commit/acac39d73b79ff9d069886ddfa92e56e905c079b)
